version: '3.8'  

services:  
  web:  
    build: .  
    ports:  
      - "5000:5000"  
    environment:  
      - ENVIRONMENT=prod

services:
  redis:
    imagr: redis:7-alpine
  ports:
    - "6379:6379"